import "./00-app-container.css";
import "./01-common-resets.css";
import "./02-theme-colors.css";
import "./03-loading-spinner.css";
import "./04-heading-text.css";
import "./05-menu-section.css";
import "./06-image-section.css";
import "./07-button-section.css";
import "./08-score-section.css";