export const EASING = {
    linear: "linear",
    easeInBack: "easeInBack",
    easeInBounce: "easeInBounce",
    easeInCirc: "easeInCirc",
    easeInCubic: "easeInCubic",
    easeInExpo: "easeInExpo",
    easeInOutBack: "easeInOutBack",
    easeInOutBounce: "easeInOutBounce",
    easeInOutCirc: "easeInOutCirc",
    easeInOutCubic: "easeInOutCubic",
    easeInOutExpo: "easeInOutExpo",
    easeInOutQuad: "easeInOutQuad",
    easeInOutQuart: "easeInOutQuart",
    easeInOutQuint: "easeInOutQuint",
    easeInOutSine: "easeInOutSine",
    easeInQuad: "easeInQuad",
    easeInQuart: "easeInQuart",
    easeInQuint: "easeInQuint",
    easeInSine: "easeInSine",
    easeOutBack: "easeOutBack",
    easeOutBounce: "easeOutBounce",
    easeOutCirc: "easeOutCirc",
    easeOutCubic: "easeOutCubic",
    easeOutExpo: "easeOutExpo",
    easeOutInBack: "easeOutInBack",
    easeOutInBounce: "easeOutInBounce",
    easeOutInCirc: "easeOutInCirc",
    easeOutInCubic: "easeOutInCubic",
    easeOutInExpo: "easeOutInExpo",
    easeOutInQuad: "easeOutInQuad",
    easeOutInQuart: "easeOutInQuart",
    easeOutInQuint: "easeOutInQuint",
    easeOutInSine: "easeOutInSine",
    easeOutQuad: "easeOutQuad",
    easeOutQuart: "easeOutQuart",
    easeOutQuint: "easeOutQuint",
    easeOutSine: "easeOutSine",
};

export const EASING_ARRAY = Object.values(EASING);