import { ICON, Theme } from "../Theme";

export const DarkTheme: Theme = {
    NAME: "Dark",
    bodyBackground: "#000000",
    mainBackground: "#000022",
    loadingSpinner: "#1c4c5b",
    titleHeading: "#ffffff",
    questionHeading: "#00ffff",
    actionLink: "#ffff00",
    imageShadow: "#a5a5c8cc",
    scoreLabel: "#00ffff",
    scoreValue: "#ffff00",
    bonus: "#00ff00",
    noBonus: "#ff0000",
    progress: "#ffffffbb",
    buttonCorrectBackground: "#007700",
    buttonCorrectText: "#ffffff",
    buttonDimmedBackground: "#44447755",
    buttonDimmedText: "#ffffff55",
    buttonDisabledBackground: "#44447755",
    buttonDisabledText: "#ffffff55",
    buttonNormalBackground: "#444477",
    buttonNormalText: "#ffffff",
    buttonWrongBackground: "#ff0000",
    buttonWrongText: "#ffffff",
    buttonRevealBackground: "#550055",
    buttonRevealText: "#ffff00",

    iconBackground: "#44447755",
    iconForeground: "#ffffffbb",

    iconSize: ICON.SIZE,
    iconStroke: ICON.STROKE,
};
