export enum ThemeName {
    dark = "dark",
    light = "light",
}

export enum ThemeColor {
    actionLink               = "actionLink",
    bodyBackground           = "bodyBackground",
    bonus                    = "bonus",
    buttonCorrectBackground  = "buttonCorrectBackground",
    buttonCorrectText        = "buttonCorrectText",
    buttonDimmedBackground   = "buttonDimmedBackground",
    buttonDimmedText         = "buttonDimmedText",
    buttonDisabledBackground = "buttonDisabledBackground",
    buttonDisabledText       = "buttonDisabledText",
    buttonNormalBackground   = "buttonNormalBackground",
    buttonNormalText         = "buttonNormalText",
    buttonRevealBackground   = "buttonRevealBackground",
    buttonRevealText         = "buttonRevealText",
    buttonWrongBackground    = "buttonWrongBackground",
    buttonWrongText          = "buttonWrongText",
    iconBackground           = "iconBackground",
    iconForeground           = "iconForeground",
    imageShadow              = "imageShadow",
    loadingSpinner           = "loadingSpinner",
    mainBackground           = "mainBackground",
    menuBackground           = "menuBackground",
    noBonus                  = "noBonus",
    progress                 = "progress",
    questionHeading          = "questionHeading",
    scoreLabel               = "scoreLabel",
    scoreValue               = "scoreValue",
    titleHeading             = "titleHeading",
}
